version:  '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    depends_on:
      - portainer
    volumes:
      - nexus_home:/nexus-data
    ports:
      - 9002:8081
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g

volumes:
  nexus_home:
  portainer_data: